title: gueco99
description: Walkthroughs y proyectos personales
baseurl: "" # subruta, dejar vacío si se despliega en la raíz
url: "https://gueco99.github.io"
repository: gueco99/gueco99.github.io

# 🔧 Tema necesario para GitHub Pages con Just the Docs
theme: just-the-docs

permalink: pretty

defaults:
  - scope:
      path: "docs"
      type: "pages"
    values:
      layout: "default"

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - bin/
  - lib/
  - "*.gemspec"
  - "*.gem"
  - LICENSE.txt
  - package.json
  - package-lock.json
  - Rakefile
  - README.md
  - CODE_OF_CONDUCT.md
  - docker-compose.yml
  - Dockerfile
  - fixtures/

search_enabled: true
search:
  heading_level: 2
  previews: 2
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false
  focus_shortcut_key: "k"

enable_copy_code_button: true

mermaid:
  version: "9.1.6"

heading_anchors: true

aux_links:
  "gueco99 on GitHub":
    - "https://github.com/gueco99"

aux_links_new_tab: true

nav_enabled: true
nav_sort: case_sensitive

nav_error_report: true

liquid:
  error_mode: strict
  strict_filters: true

back_to_top: true
back_to_top_text: "Back to top"

footer_content: 'Creado por gueco99. Desplegado en GitHub Pages usando Just the Docs.'

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

gh_edit_link: true
gh_edit_link_text: "Edita esta página en GitHub"
gh_edit_repository: "https://github.com/gueco99/gueco99.github.io"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"

color_scheme: nil

callouts_level: quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-sitemap

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
